/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutCard: typeof import('./src/components/AboutCard.vue')['default']
    ContactsCard: typeof import('./src/components/ContactsCard.vue')['default']
    EducationCard: typeof import('./src/components/EducationCard.vue')['default']
    ExperienceCard: typeof import('./src/components/ExperienceCard.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RepoCard: typeof import('./src/components/RepoCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechCard: typeof import('./src/components/TechCard.vue')['default']
  }
}
